FROM python:3

ENV PYTHONUNBUFFERED 0

RUN apt-get -y install \
    libpq-dev

WORKDIR /app

ADD    requirements.txt    /app/
RUN    pip install -r requirements.txt
ADD    https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /