version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/code
            - ./config/nginx:/etc/nginx.conf.d
        depends_on: 
            - web

    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn deployment.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code
        expose:
            - "8000"